### ISSUE TITLE
ReactomeFIViz BuildFISubNetwork fails via command line when useLinkers=True

### ISSUE THREAD

**Issue by Niveda-S** [reactome-fi/CytoscapePlugIn#5]
Hi,

I'm trying to run ReactomeFIViz  cytoscape plugin command line, but I encounter a index=0 error when I use the following parameters:
`body = dict(fiVersion='2017', format='GeneSet', enteredGenes=join_genes, useLinkers=True, showUnLinked=False, fetchFIAnnotations=True)`  
where join_genes = comma separated list of genes.

However using the same command but with useLinkers=False seems to work. Please let me know why this is the case. Am I missing something in my statement?

**Comment by guanmingwu** [comment]
Hi Niveda,

Could you please make sure you use “\n” in the join_genes variable in the dict() function in your Python code? If you are using a file, please make sure one gene per line.

There is a bug in the Swagger doc: It should use “\n”, instead of “,”, to separate genes, i.e., the following should be used for the example of buildFISubNetwork:

"enteredGenes": "EGF\nEGFR\nKRAS\nTP53”,

We will update the doc for our next release of ReactomeFIViz.

Thanks a lot for your interest in our project and especially reporting the bug to us.

Guanming

P.S.: Please be aware it will take much longer time to use linker to build a FI subnetwork. Usually we don’t recommend if you have a long list of genes (e.g. > several hundreds).

**Comment by Niveda-S** [comment]
Thanks for the clarification. This works now!
